# Generated by Django 3.0.8 on 2020-08-17 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
