# Generated by Django 3.0.8 on 2020-08-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200817_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
