# Generated by Django 3.0.8 on 2020-08-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200817_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
